### ISSUE TITLE
Allow .help line limit to be set in config

### ISSUE THREAD

**Issue by MacFan4000** [sopel-irc/sopel-help#2]
### The problem
We have found that in plenty of cases (such as wth .urlexclude and .urlallow) the help messages are said to be too long and then are subsequently sent in a PM. Looking at the messages, the help text isn't that long, and it is because in the code there is a blank line between sentences.

### The solution
Allow the help text length threshold to set in config. This would allow users to set it to a value that is good for them.

### Alternatives
You could also increase the limit of fix the individual cases, but it's probably better to allow users to control the limit rather then setting a hard unchangeable limit in the code.

### Notes
There is currently an unchangeable hard limit of 3 lines. (https://github.com/sopel-irc/sopel-help/blob/master/sopel_help/providers.py#L90)

This is the same issue reported in sopel-irc/sopel#2045

**Comment by dgw** [comment]
@Exirel The excess blank lines could be an extra improvement opportunity, btw 🙃
